const GOOGLE_API_SPREADSHEETS_ID = process.env.GOOGLE_API_SPREADSHEETS_ID;
const GOOGLE_API_SPREADSHEETS_CLIENT_EMAIL = process.env.GOOGLE_API_SPREADSHEETS_CLIENT_EMAIL;
const GOOGLE_API_SPREADSHEETS_PRIVATE_KEY = process.env.GOOGLE_API_SPREADSHEETS_PRIVATE_KEY;

module.exports = {
    PORT: process.env.PORT || 5000,
    GOOGLE_API_SPREADSHEETS_ID,
    GOOGLE_API_SPREADSHEETS_CLIENT_EMAIL,
    GOOGLE_API_SPREADSHEETS_PRIVATE_KEY
};